apiVersion: v2
name: grafana-monitoring
description: A Helm chart for gathering, scraping, and forwarding Kubernetes telemetry data to a Grafana Stack.
type: application
version: 1.2.6

sources:
  - https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring-v1

dependencies:
  - name: k8s-monitoring
    repository: https://grafana.github.io/helm-charts
    version: 2.1.4
