apiVersion: v2
name: descheduler
description: A Helm chart for Kubernetes
type: application
version: 1.0.0

dependencies:
- name: descheduler
  version: 0.31.0 
  repository: https://kubernetes-sigs.github.io/descheduler/