# More information on configuring homepage: https://gethomepage.dev/main/

config:
  custom_css: ""
  custom_js: ""
  settings: ""
  kubernetes:
    mode: cluster
  bookmarks:
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services:
    - My First Group:
        - My First Service:
            href: http://localhost/
            description: Homepage is awesome

    - My Second Group:
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  # bookmarks:
  #   - Developer:
  #     - Github:
  #       - abbr: GH
  #         icon: github.svg
  #         href: https://github.com
  # services:
  #   - My First Group:
  #     - My First Service:
  #         href: http://localhost/
  #         description: Homepage is awesome

  #   - My Second Group:
  #     - My Second Service:
  #         href: http://localhost/
  #         description: Homepage is the best

  #   - My Third Group:
  #     - My Third Service:
  #         href: http://localhost/
  #         description: Homepage is 😎
  widgets:
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker: ""