metadata:
  service: homepage
  environment: homepage
  managedBy: fluxcd

# More information on configuring homepage: https://gethomepage.dev/main/

configuration:
  kubernetes_yaml: |
    mode: cluster
  settings_yaml: ""
  custom_css: ""
  custom_js: ""
  bookmarks_yaml: |
    - Developer:
        - Github:
            - abbr: GH
              icon: github.svg
              href: https://github.com
  services_yaml: |
    - My First Group:
          - My First Service:
                href: http://localhost/
                description: Homepage is awesome

    - My Second Group:
          - My Second Service:
                href: http://localhost/
                description: Homepage is the best

    - My Third Group:
          - My Third Service:
                href: http://localhost/
                description: Homepage is 😎
  widgets_yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker_yaml: ""