{{- define "common.secret.tpl" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.metadata.name" . }}
  labels:
    {{ include "common.metadata.labels" . | indent 4 }}
{{- end }}

{{- define "common.secret" -}}
{{- include "common.util.merge" (append . "common.secret.tpl") -}}
{{- end -}}
---
