{{- define "common.service_account.tpl" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.metadata.name" . }}
  labels:
    {{ include "common.metadata.labels" . | indent 4 }}
{{- end }}

{{- define "common.service_account" -}}
{{- include "common.util.merge" (append . "common.service_account.tpl") -}}
{{- end -}}
---
