apiVersion: v1
kind: Service
metadata:
  labels:
    application: {{ .Release.Name }}
    component: frontend
  name: {{ .Release.Name }}
spec:
  selector:
    application: {{ .Release.Name }}
    component: frontend
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080