# Manifests obtained from https://codeberg.org/hjacobs/kube-ops-view/src/branch/main/deploy
apiVersion: v2
name: kubelet-serving-cert-approver
version: 1.0.1

dependencies:
- name: common
  version: 0.1.0
  repository: file://../common
