{{- include "common.secret" (list . "kube-cats.secret") }}
{{- define "kube-cats.secret" }}
type: kubernetes.io/service-account-token
metadata:
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name }}
{{- end }}