{{- include "common.service" (list . "kube-cats.service") }}
{{- define "kube-cats.service" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    application: {{ .Release.Name }}
    component: web
  name: {{ .Release.Name }}
spec:
  selector:
    application: {{ .Release.Name }}
    component: web
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
{{- end }}
---
{{- include "common.service" (list . "kube-cats-api.service") }}
{{- define "kube-cats-api.service" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    application: {{ .Release.Name }}-api
    component: api
  name: {{ .Release.Name }}-api
spec:
  selector:
    application: {{ .Release.Name }}-api
    component: api
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
{{- end }}
