{{- include "common.configmap" (list . "homepage.configmap") }}
{{- define "homepage.configmap" }}
data:
  kubernetes.yaml: |
{{ toYaml .Values.config.kubernetes | indent 4 | default "" }}
  settings.yaml: |
{{ toYaml .Values.config.settings | indent 4 | default "" }}
  custom.css: |
{{ toYaml .Values.config.custom_css | indent 4 | default "" }}
  custom.js: |
{{ toYaml .Values.config.custom_js | indent 4 | default "" }}
  bookmarks.yaml: |
{{ toYaml .Values.config.bookmarks | indent 4 | default "" }}
  services.yaml: |
{{ toYaml .Values.config.services | indent 4 | default "" }}
  widgets.yaml: |
{{ toYaml .Values.config.widgets | indent 4 | default "" }}
  docker.yaml: |
{{ toYaml .Values.config.docker | indent 4 | default "" }}
{{- end }}
