{{- include "common.configmap" (list . "homepage.configmap") }}
{{- define "homepage.configmap" }}
data:
  kubernetes.yaml: {{ .Values.configuration.kubernetes_yaml | default "" }}
  settings.yaml: {{ .Values.configuration.settings_yaml | default "" }}
  custom.css: {{ .Values.configuration.custom_css | default "" }}
  custom.js: {{ .Values.configuration.custom_js | default "" }}
  bookmarks.yaml: {{ .Values.configuration.bookmarks_yaml | default "" }}
  services.yaml: {{ .Values.configuration.services_yaml | default "" }}
  widgets.yaml: {{ .Values.configuration.widgets_yaml | default "" }}
  docker.yaml: {{ .Values.configuration.docker_yaml | default "" }}
{{- end }}
