apiVersion: v2
name: onepassword-connect
description: A Helm chart for Kubernetes
type: application
version: 1.0.3

dependencies:
  - name: connect
    version: 1.16.0
    repository: https://1password.github.io/connect-helm-charts
