apiVersion: v2
name: onepassword-connect
description: A Helm chart for Kubernetes
type: application
version: 1.0.2

dependencies:
  - name: connect
    version: 1.15.1
    repository: https://1password.github.io/connect-helm-charts
