kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080