name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: add repos
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo add podinfo https://stefanprodan.github.io/podinfo
          helm repo add mend https://mend.github.io/renovate-ce-ee
          helm repo add emberstack https://emberstack.github.io/helm-charts
          helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller
          helm repo add gatekeeper https://open-policy-agent.github.io/gatekeeper/charts
          helm repo add cilium https://helm.cilium.io/
          helm repo add external-secrets https://charts.external-secrets.io
          helm repo add opencost https://opencost.github.io/opencost-helm-chart
          helm repo add cloudflare https://cloudflare.github.io/helm-charts
          helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server
          helm repo add descheduler https://kubernetes-sigs.github.io/descheduler/
          helm repo add crossplane https://charts.crossplane.io/stable
          helm repo add jetstack https://charts.jetstack.io
          # helm repo add headlamp https://headlamp-k8s.github.io/headlamp/
          helm repo add onepassword https://1password.github.io/connect-helm-charts
          helm repo add backube https://backube.github.io/helm-charts/
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add authentik https://charts.goauthentik.io
          helm repo add stakater https://stakater.github.io/stakater-charts
          helm repo add minio https://operator.min.io
          helm repo add metallb https://metallb.github.io/metallb
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add rook-release https://charts.rook.io/release
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add fairwinds https://charts.fairwinds.com/stable
          helm repo add external-dns https://kubernetes-sigs.github.io/external-dns
          helm repo add twin https://twin.github.io/helm-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: charts